/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Constructores_GUI;

import BoxTools.BoxPlace;
import Map_Initializer.Bank;
import Map_Initializer.PlayerHandler;
import Player.Player;

/**
 *
 * @author camran
 */
public class Buscador extends javax.swing.JFrame {

    private Bank bank;
    private Player player;
    private boolean decision;
    /**
     * Creates new form Buscador
     * Coloca falso para obtener propiedades hipotecadas
     * Coloca verdadero para obtener propiedades con capacidad de construccion
     */
    public Buscador(Bank bank, Player player, boolean decision) {
        this.bank = bank;
        this.player = player;
        this.decision = decision;
        initComponents();
        asignarComponentes();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setOpaque(true);
        jPanel1.setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Propiedad");

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jButton1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(207, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(jComboBox1.getSelectedItem()!=null){
            String propiedad = jComboBox1.getSelectedItem().toString();

            if(decision==true){
                for(int index=0;index<bank.getPropiedades().length;index++){
                    if(bank.getPropiedades()[index].getName().equalsIgnoreCase(propiedad) && bank.getPropiedades()[index] instanceof BoxPlace) {
                        new Construcciones( (BoxPlace)bank.getPropiedades()[index],bank);
                        break;
                    }
                }
            }else{
                for(int index=0;index<bank.getPropiedades().length;index++){
                    if(bank.getPropiedades()[index].getName().equalsIgnoreCase(propiedad)) {
                        new Hipotecar(bank.getPropiedades()[index],player);
                        break;
                    }
                }

                for(int index=0;index<player.getCards().length;index++){
                    if( jComboBox1.getSelectedItem().toString().equalsIgnoreCase("Jail")){
                        new Hipotecar(player);
                        break;
                    }
                }
            }
            this.setVisible(false);
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void asignarComponentes(){
        if(decision==true){
            for(int index=0;index<bank.getPropiedades().length;index++){
                if(bank.getPropiedades()[index].getOwner().equalsIgnoreCase(player.getNombre()) && bank.getPropiedades()[index] instanceof BoxPlace) {
                    jComboBox1.addItem(bank.getPropiedades()[index].getName());
                }
            }
        }else{
            for(int index=0;index<bank.getPropiedades().length;index++){
                if(bank.getPropiedades()[index].getOwner().equalsIgnoreCase(player.getNombre())) {
                    jComboBox1.addItem(bank.getPropiedades()[index].getName());
                }
            }
            
            for(int index=0;index<player.getCards().length;index++){
                    jComboBox1.addItem(player.getCards()[index].getData());
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
